### ISSUE TITLE
"KeyError: 'nodes'" on macOS

### ISSUE THREAD

**Issue by lemmy** [harmonylang/harmonylang#46]
1) Install the VSCode extension
2) Installed Harmony on macOS 12.6 with `python3 -m pip install harmony-model-checker`
```zsh
markus@avocado [11:02:10] [~/src/Harmony]
-> % /opt/homebrew/bin/harmony -v
Version: harmony_model_checker 1.2.2769
```

With e.g., `triangle.hny` from https://harmony.cs.cornell.edu/docs/textbook/harmonyintro/:

```zsh
Phase 1: compile Harmony program to bytecode
Phase 2: run the model checker
nworkers = 10
#states 13 (time 0.000+0.000=0.000)
Phase 3: analysis
13 components (0.000 seconds)
Check for data races
No issues
Phase 4: write results to /var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tmp-83212-za2cf6avY7Mc.hco
Phase 5: loading /var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tmp-83212-za2cf6avY7Mc.hco

Command failed: /opt/homebrew/bin/harmony -o /var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tmp-83212-za2cf6avY7Mc.hvm -o /var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tmp-83212-za2cf6avY7Mc.hco -o /var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tmp-83212-za2cf6avY7Mc.htm -o /var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tmp-83212-za2cf6avY7Mc.gv --noweb /Users/markus/src/Harmony/triangle.hny
Traceback (most recent call last):
  File "/opt/homebrew/bin/harmony", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/harmony_model_checker/main.py", line 260, in main
    handle_hco(ns, output_files)
  File "/opt/homebrew/lib/python3.10/site-packages/harmony_model_checker/main.py", line 139, in handle_hco
    b.run(output_files, behavior)
  File "/opt/homebrew/lib/python3.10/site-packages/harmony_model_checker/harmony/brief.py", line 140, in run
    behavior_parse(top, False, outputfiles, behavior)
  File "/opt/homebrew/lib/python3.10/site-packages/harmony_model_checker/harmony/behavior.py", line 240, in behavior_parse
    for s in js["nodes"]:
KeyError: 'nodes'
```

**Comment by anthonyyangdev** [comment]
The issue is caused by Harmony model checker not outputting `nodes` as a key in the output `*.hco` file, which happens when the Harmony program doesn't contain any `print` statements. If you add a print statement in the `triangle.hny` program, then it should run without issues.

This issue should be fixed in the model checker, rather than VSCode extension.

**Comment by lemmy** [comment]
When a user checks the original `triangle.hny` (the one from the documentation) on the command-line, no error is raised:

```shell
-> % /opt/homebrew/bin/harmony --noweb triangle.hny
Phase 1: compile Harmony program to bytecode
Phase 2: run the model checker
nworkers = 10
#states 13 (time 0.000+0.000=0.000)
Phase 3: analysis
13 components (0.000 seconds)
Check for data races
No issues
Phase 4: write results to triangle.hco
Phase 5: loading triangle.hco
open file:///Users/markus/src/Harmony/triangle.htm for more information
```
